### Trabalho 1 - MIneração de dados
O objetivo deste exercício é explorar, tratar e visualizar dados públicos do Brasil disponibilizados pelo IBGE, aplicando técnicas de mineração de dados e construção de gráficos estatísticos.

Os datasets escolhidos foram: 
- PIB dos Municípios – dados econômicos por cidade.
- SIDRA (Sistema IBGE de Recuperação Automática)

In [5]:
import pandas as pd
import numpy as np
from pathlib import Path

caminho1 = Path("datas/PIBMunicipios.csv")
caminho2 = Path("datas/SIDRA.xlsx")

df_pib = pd.read_csv(caminho1, sep=';', skiprows=1, nrows=1, encoding='utf-8')
df_sidra = pd.read_excel(caminho2, skiprows= 3)

display(df_pib)
display(df_sidra)

,Acre,Alagoas,Amapá,Amazonas,Bahia,Ceará,Distrito Federal,Espírito Santo,Goiás,Maranhão,...,Piauí,Rio Grande do Norte,Rio Grande do Sul,Rio de Janeiro,Rondônia,Roraima,Santa Catarina,Sergipe,São Paulo,Tocantins
0,26291321,89688932,28020120,161794976,430987853,232239257,365669108,209829732,336746975,149227195,...,80916856,101740275,650107022,1172871443,76456179,25124805,513392973,60816662,3444814033,64317699

,Unnamed: 0,Índice de base fixa mensal sem ajuste sazonal (Base: média de 2022 = 100),Índice de base fixa mensal com ajuste sazonal (Base: média de 2022 = 100),Variação percentual mês/mês imediatamente anterior com ajuste sazonal (Base: mês imediatamente anterior) (%),Variação percentual mensal (Base: igual mês do ano anterior) (%),Variação percentual acumulada no ano (Base: igual período do ano anterior) (%),Variação percentual acumulada nos últimos 12 meses (Base: últimos 12 meses anteriores) (%)
0,1 - Indústria geral,111.69150,104.00233,0.2,-0.5,1.1,0.6
1,2 - Indústrias extrativas,123.56076,117.37323,-1.0,2.5,6.7,6.5
2,3 - Indústrias de transformação,109.66804,101.78315,0.5,-1.1,0.1,-0.5
3,3.10 - Fabricação de produtos alimentícios,116.37867,104.74852,1.0,-2.6,0.4,2.0
4,3.11 - Fabricação de bebidas,94.90007,101.34791,0.8,5.0,1.9,0.0
5,3.12 - Fabricação de produtos do fumo,185.69487,133.38523,11.1,23.6,5.4,8.9
6,3.13 - Fabricação de produtos têxteis,115.84640,106.66194,0.2,-6.8,-3.9,-1.9
7,3.14 - Confecção de artigos do vestuário e ace...,97.71084,89.24585,2.6,-8.2,-6.8,-4.2
8,3.15 - Preparação de couros e fabricação de ar...,105.51537,96.87318,-1.0,-3.5,-4.8,-4.1
9,3.16 - Fabricação de produtos de madeira,100.01916,96.26510,0.2,-0.3,-3.0,-6.6
10,"3.17 - Fabricação de celulose, papel e produto...",104.78460,101.09617,-1.3,0.0,-1.9,0.0
11,3.18 - Impressão e reprodução de gravações,97.03020,91.01627,-17.2,0.6,-2.3,-1.0
12,"3.19 - Fabricação de coque, de produtos deriva...",115.19758,102.16548,1.1,0.6,3.7,-1.4
13,3.20 Fabricação de produtos químicos,101.06285,92.80147,-0.8,-6.9,-3.4,-3.0
14,3.21 - Fabricação de produtos farmoquímicos e ...,97.41078,93.22976,-0.8,-13.7,5.8,7.1
15,3.22 - Fabricação de produtos de borracha e de...,111.62034,106.51715,-0.4,-2.3,0.5,0.7
16,3.23 - Fabricação de produtos de minerais não ...,106.17672,99.34675,0.5,3.7,0.8,0.0
17,3.24 - Metalurgia,108.00601,103.32995,-1.4,2.4,0.7,0.0
18,"3.25 - Fabricação de produtos de metal, exceto...",103.87791,97.03812,0.8,0.2,-2.9,-4.2
19,3.26 - Fabricação de equipamentos de informáti...,96.97601,95.69044,12.2,-2.4,-4.7,-4.8
20,"3.27 - Fabricação de máquinas, aparelhos e mat...",108.91438,103.95080,2.3,6.4,-0.3,-2.2
21,3.28 - Fabricação de máquinas e equipamentos,100.03210,93.89745,-0.1,-6.3,-7.5,-4.0
22,"3.29 - Fabricação de veículos automotores, reb...",122.71535,115.19088,-0.1,7.6,5.7,0.8
23,3.30 - Fabricação de outros equipamentos de tr...,125.04441,120.20977,11.2,1.7,-2.7,-0.5
24,3.31 - Fabricação de móveis,109.02155,101.68739,-0.6,-6.6,-2.3,-3.2
25,3.32 - Fabricação de produtos diversos,92.97438,85.30450,-9.0,-12.0,-1.1,3.3
26,"3.33 - Manutenção, reparação e instalação de m...",111.53185,105.22881,0.8,1.9,1.8,4.2
27,Fonte: IBGE - Pesquisa Industrial Mensal - Pro...,NaN,NaN,NaN,NaN,NaN,NaN